# Generated by Django 5.2.5 on 2025-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
